#+TITLE: Emacs Configuration

This is an experiment to create an Emacs configuration with modal editing using
keybindings inspired by [[https://github.com/xahlee/xah-fly-keys][xah-fly-keys]], yet for the [[https://colemakmods.github.io/mod-dh/][Colemak mod-DH]] keyboard layout.

Although I copy the concept used in xah-fly-keys that for normal mode the position of a
key should determine the functionality I prefer to use more mnemonic commands for prefix
keys than result when remapping the used Dvorak bindings in xah-fly-keys to Colemak Mod
DH.

* Core ideas
This configuration uses the [[https://github.com/Kungsgeten/ryo-modal][ryo-modal]] package to set up a modal configuration in
the form of a minor mode. This allows me to create bindings that can be bound to sequence
of characters of my own choosing. Although the same can be achieved with xah-fly-keys
directly this makes it easier to define keys only bound in specific major modes.

To ensure that this configuration is reproducible between different machines packages are
installed and managed using [[https://github.com/raxod502/straight.el][straight.el]], which integrates well with [[https://github.com/jwiegley/use-package][use-package]].
